### ISSUE TITLE
Expose a global bin

### ISSUE THREAD

**Issue by searls** [blainesch/pry.js#35]
When I ran `npm i -g pryjs`, I expected to be able to run `pryjs` from the command line, just like I would with Ruby pry. 

Thoughts on this?

**Comment by blainesch** [comment]
What is the use case for needing this?

Most of the available commands are only useful for gathering context-sensitive things such as `wtf` or `play`. The benefit I can see is being able to switch modes from js to coffee, otherwise it'll be almost identical to just running `node` or `coffee`, right?

I believe Pry has a lot more useful commands for browsing code and documentation, which I've not found a great way to do in Node. This could make it much more useful without being in an actual breakpoint.

What do you think?

**Comment by searls** [comment]
Well, given that 90% of my usage of pry for ruby is simply using it as a pluggable repl that's far more ergonomic to use than `irb`, I figured that whatever ergonomic (color, custom introspective commands like `ls` and so forth) you implemented for pry.js would carry over to being good reasons for improving on the (IMO) absolutely awful `node` REPL experience.

**Comment by blainesch** [comment]
Fixed by 211dd65ee020ad9d6a33758860f8ac30defc2bef

**Comment by searls** [comment]
Yay!
